import Head from 'next/head'
import LoginForm from '@/component/Forms/LoginForm'
import { Inter } from '@next/font/google'
import margin from "../styles/margins.module.scss";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Interview Managemnt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className = {margin.login} >
          <LoginForm/>
        </div>
    </>
  )
}
